logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

spring:
  rabbitmq:
    host: 49.234.5.89
    virtual-host: /
    username: itcast
    password: 123321
    port: 5672
    listener:
      simple:
        prefetch: 1 #控制消费者从queue中获取的消息，就是消费玩了之后再拿